INDUSTRIES = ['Advertising',
              'Agriculture and Forestry',
              'Architects',
              'Arts and Cultures Industries',
              'Catering',
              'Charities', 'Clubs and Associations',
              'Construction Industry',
              'Dentists',
              'Distribution and Transport',
              'Doctors',
              'Education',
              'Engineering',
              'Entertainment',
              'Estate Agents',
              'Financial Services',
              'Friendly Societies',
              'Housing',
              'IT/Software',
              'Manufacturing',
              'Motor Retailers',
              'Printing and Publishing',
              'Public sector',
              'Retail',
              'Service Industries',
              'Solicitors',
              'Sub-Contractors',
              'Telecommunications',
              'Tourism and Travel Agents',
              'Vets']

COMPANY_SIZES = ['<1', '1-10', '10-25', '25+']

SUBSERVICES = ["Business start-up and company formation",
            "Information Technology",
            "Limited company accounts",
            "Partnership / sole trader accounts",
            "Business plans",
            "Management advice to business",
            "Tax(CGT, Corporate, IHT, Personal and VAT)",
            "Company secretarial service",
            "Corporate finance",
            "Management accounting consultancy",
            "Management consultancy",
            "Share valuations",
            "Tax and NI investigations",
            "Benchmarking",
            "Business process improvements",
            "Corporate recovery",
            "Cost systems and control",
            "Data processing services",
            "Debt counselling",
            "Estate planning and executorship",
            "Expert witness",
            "Feasibility studies",
            "Internal audit and systems security",
            "Trusteeship / Trust Administration",
            "Bank loans and overdrafts (inc SFLGS)",
            "Business risk assessment",
            "Business plans (external and internal)",
            "Small scale equity issues",
            "Start-up Finance(inc using own funds)",
            "Divorce matrimonial",
            "Export finance planning and tax",
            "Grants and Finance (EU,government)",
            "Treasury",
            "Establishing a business overseas",
            "Arbitration",
            "Environmental auditing",
            "Leasing and hire purchase",
            "Asset Finance",
            "Annual Accounts",
            "Audit Services",
            "Business Advice",
            "Tax Services",
            "M&A/Transaction",
            "Bookkeeping",
            "Other"]

SERVICES = [ "Annual Accounts",
             "Audit Services",
             "Business Consulting & Support",
             "Tax Services",
             "Formation / M&A",
             "Bookkeeping & Admin",
             "Insolvency and Arbitration",
             "Financing Support",
             "Other"]

SERVICE_MAP = {
  "Business start-up and company formation" => "Formation / M&A",
  "Information Technology" => "Bookkeeping & Admin",
  "Limited company accounts" => "Annual Accounts",
  "Partnership / sole trader accounts" => "Annual Accounts",
  "Business plans" => "Business Consulting & Support",
  "Management advice to business" => "Business Consulting & Support",
  "Tax(CGT, Corporate, IHT, Personal and VAT)" => "Tax Services",
  "Company secretarial service" => "Bookkeeping & Admin",
  "Corporate finance" => "Financing Support",
  "Management accounting consultancy" => "Business Consulting & Support",
  "Management consultancy" => "Business Consulting & Support",
  "Share valuations" => "Financing Support",
  "Tax and NI investigations" => "Tax Services",
  "Benchmarking" => "Business Consulting & Support",
  "Business process improvements" => "Business Consulting & Support",
  "Corporate recovery" => "Insolvency and Arbitration",
  "Cost systems and control" => "Bookkeeping & Admin",
  "Data processing services" => "Bookkeeping & Admin",
  "Debt counselling" => "Financing Support",
  "Estate planning and executorship" => "Other",
  "Expert witness" => "Other",
  "Feasibility studies" => "Other",
  "Internal audit and systems security" => "Audit Services",
  "Trusteeship / Trust Administration" => "Other",
  "Bank loans and overdrafts (inc SFLGS)" => "Financing Support",
  "Business risk assessment" => "Business Consulting & Support",
  "Business plans (external and internal)" => "Business Consulting & Support",
  "Small scale equity issues" => "Financing Support",
  "Start-up Finance(inc using own funds)" => "Financing Support",
  "Divorce matrimonial" => "Insolvency and Arbitration",
  "Export finance planning and tax" => "Tax Services",
  "Grants and Finance (EU,government)" => "Financing Support",
  "Treasury" => "Other",
  "Establishing a business overseas" => "Formation / M&A",
  "Arbitration" => "Insolvency and Arbitration",
  "Environmental auditing" => "Audit Services",
  "Leasing and hire purchase" => "Other",
  "Asset Finance" => "Financing Support",
  "Annual Accounts" => "Annual Accounts",
  "Audit Services" => "Audit Services",
  "Business Advice" => "Business Consulting & Support",
  "Tax Services" => "Tax Services",
  "M&A/Transaction" => "Formation / M&A",
  "Bookkeeping" => "Bookkeeping & Admin",
  "Other" => "Other"
}

QUALIFICATIONS = ['ACCA']
