INDUSTRIES = ['Advertising',
              'Agriculture & Forestry',
              'Architects',
              'Arts & Cultures Industries',
              'Catering (Pubs, Restaurants, Food and Drink)',
              'Charities', 'Clubs and Associations',
              'Construction Industry',
              'Dentists',
              'Distribution & Transport',
              'Doctors',
              'Education',
              'Engineering',
              'Entertainment',
              'Estate Agents',
              'Financial Services',
              'Friendly Societies',
              'Housing',
              'IT/Software',
              'Manufacturing',
              'Motor Retailers',
              'Printing and Publishing',
              'Public Sector',
              'Retail',
              'Service Industries',
              'Solicitors',
              'Sub-Contractor',
              'Telecommunications',
              'Tourism and Travel Agents',
              'Vets']

COMPANY_SIZES = ['<1', '1-10', '10-25', '25+']

SERVICES = ['Annual Accounts',
            'Audit Services',
            'Business Advice',
            'Tax Services',
            'M&A/Transaction',
            'Bookkeeping',
            'Other']
