INDUSTRIES = ['Advertising',
              'Agriculture & Forestry',
              'Architects',
              'Arts & Cultures Industries',
              'Catering (Pubs, Restaurants, Food and Drink)',
              'Charities', 'Clubs and Associations',
              'Construction Industry',
              'Dentists',
              'Distribution & Transport',
              'Doctors',
              'Education',
              'Engineering',
              'Entertainment',
              'Estate Agents',
              'Financial Services',
              'Friendly Societies',
              'Housing',
              'IT/Software',
              'Manufacturing',
              'Motor Retailers',
              'Printing and Publishing',
              'Public Sector',
              'Retail',
              'Service Industries',
              'Solicitors',
              'Sub-Contractor',
              'Telecommunications',
              'Tourism and Travel Agents',
              'Vets']

COMPANY_SIZES = ['<1', '1-10', '10-25', '25+']

SERVICES = ["Business start-up and company formation",
            "Information Technology",
            "Limited company accounts",
            "Partnership / sole trader accounts",
            "Business plans",
            "Management advice to business",
            "Tax(CGT, Corporate, IHT, Personal and VAT)",
            "Company secretarial service",
            "Corporate finance",
            "Management accounting consultancy",
            "Management consultancy",
            "Share valuations",
            "Tax and NI investigations",
            "Benchmarking",
            "Business process improvements",
            "Corporate recovery",
            "Cost systems and control",
            "Data processing services",
            "Debt counselling",
            "Estate planning and executorship",
            "Expert witness",
            "Feasibility studies",
            "Internal audit and systems security",
            "Trusteeship / Trust Administration",
            "Bank loans and overdrafts (inc SFLGS)",
            "Business risk assessment",
            "Business plans (external and internal)",
            "Small scale equity issues",
            "Start-up Finance(inc using own funds)",
            "Divorce matrimonial",
            "Export finance planning and tax",
            "Grants and Finance (EU,government)",
            "Treasury",
            "Establishing a business overseas",
            "Arbitration",
            "Environmental auditing",
            "Leasing and hire purchase",
            "Asset Finance",
            "Annual Accounts",
            "Audit Services",
            "Business Advice",
            "Tax Services",
            "M&A/Transaction",
            "Bookkeeping",
            "Other"]

QUALIFICATIONS = ['ACCA']
