meta_product_name: "magnet."
meta_title: "magnet. | Find the accountants that know your business and are trusted by your network"
meta_description: "Magnet will help bring the accountants that know your business to you. We listen to exactly what you need, and recommend the best accountants for the job"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@TO_ADD"   # required for Twitter Cards
