meta_product_name: "magnet."
meta_title: "magnet. | The best accountants for your business. Brought to you."
meta_description: "We listen to exactly what you need, and recommend the best accountants for the job."
meta_image: "magnet-cover.jpg"                       # should exist in `app/assets/images/`
twitter_account: "@TO_ADD"   # required for Twitter Cards
